version: '3.9'

services:
  db:
    image: postgres:15
    container_name: online-shop-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 503812
      POSTGRES_DB: online-shop
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  basket-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basket-service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/online-shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 503812
      SERVER_PORT: 9090
    ports:
      - "9090:9090"

volumes:
  pgdata:
