spring:
  application:
    name: basket
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/online-shop
    username: postgres
    password: 503812
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090